### ISSUE TITLE
Release 1.3 is not on pypi

### ISSUE THREAD

**Issue by twidi** [Maillol/cricri#2]
The release on was tagged on git a few weeks ago, but on PyPi the last available version is the 1.2: https://pypi.python.org/pypi/cricri

**Comment by Maillol** [comment]
I upload the release 1.3 on pypi today. Maybe I have an issue with twine
and the pypi default url

Thanks for alerting me

**Comment by twidi** [comment]
Thanks to you (btw I saw your talk @pyconFR, I really like your library!)
